name: "MacOS Test!"
run-name: "MacOS Test! Run NAME"
on:
  push:

  # Githubにて「Actions」タブを洗濯後、左エリアの「name」を選択すると、「Run workflow」が表示される。
  workflow_dispatch:
    inputs:
      flavor-must:
        required: true
        description: 'Flavor Must'
        default: 'default-value 1'
      flavor-not-must:
        required: false
        description: 'Flavor Not Must'
        default: 'default-value 2'

jobs:
  macos_test:
    runs-on: macos-latest
    steps:
      - name: '@@ actions/checkout@v4'
        uses: actions/checkout@v4

      - name: 'cd ./android'
        uses: cd ./android

      - name: 'pwd'
        uses: pwd

      - name: './gradlew assembleDebug'
        uses: ./gradlew assembleDebug


#      - name: '@@actions/upload-artifact@v4'
#        uses: actions/upload-artifact@v4
#        with:
#          name: outputs
#          path: ./outputs